Repository selsa-inube/inubekit-button, pull requests merged in 2024-09, with the labels that each got.

#39 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#40 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#41 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#42 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#43 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#44 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#45 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#46 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#47 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#48 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#49 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#50 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#52 fix: flex layout with gap and button padding with props
  src/Button/Button.stories.tsx
  src/Button/index.tsx
  src/Button/styles.js
Labels: patch

#53 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#54 Move button tokens from foundations to component
  src/Button/Tokens/tokens.ts
  src/Button/index.tsx
  src/Button/styles.js
Labels: minor

#55 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#56 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#57 Update text dependency to latest version
  package.json
Labels: minor, dependencies
