Repository selsa-inube/inubekit-button, pull requests merged in 2024-03, with the labels that each got.

#2 Refactor component to use new tokens, and component dependencies (text, icon).
  README.md
  package-lock.json
  package.json
  src/Button/Button.stories.tsx
  src/Button/index.tsx
  src/Button/props.ts
  src/Button/styles.js
  vite.config.ts
Labels: major

#4 Update foundations dependency
  package-lock.json
  package.json
  src/Button/styles.js
Labels: patch, dependencies

#6 Adjust and export interfaces
  src/Button/index.tsx
  src/Button/props.ts
  src/index.ts
Labels: minor

#7 Update all inubekit/button to storybook v8
  package-lock.json
  package.json
Labels: dependencies

#8 Publish new version 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
